# FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
# ENTRYPOINT ["dotnet", "CourseManagement.dll"]
# ENTRYPOINT ["dotnet", "Docker.Compose.API.dll"]

# COPY ["Docker.Compose.API.csproj", "Docker.Compose.API/"]
# RUN dotnet restore "./Docker.Compose.API.csproj"